version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - '6381:6379'

  consul1:
    image: consul
    container_name: node1
    ports:
      - "18500:18500"
    command: agent -server -bootstrap-expect 3 -ui -disable-host-node-id -client 0.0.0.0 -bind 0.0.0.0

  consul2:
    image: consul
    container_name: node2
    ports:
      - "18501:18501"
    command: agent -server -ui -join node1 -disable-host-node-id -client 0.0.0.0 -bind 0.0.0.0
    depends_on:
      - consul1

  consul3:
    image: consul
    container_name: node3
    ports:
      - "18502:18502"
    command: agent -server -ui -join node1 -disable-host-node-id -client 0.0.0.0 -bind 0.0.0.0
    depends_on:
      - consul1

  pwm:
    image: pwm:v1.1.1-8
    ports:
      - '88:888'
    links:
      - redis
      - consul1
    environment:
      - CONSUL_IP=consul1
      - MONTIOR_REDIS=redis
      - ALERTMANAGER_HTTP=10.50.182.65:9300
      - REDIS_IP=redis
      - REDIS_PORT=6381
      - MONTIOR_PORT=6381
      - CONSUL_PORT=18500
    depends_on:
      - redis
      - consul3
  pwm-web:
    image: pwm-web:v1.1.1-28
    links:
      - pwm
    ports:
      - '8088:8080'
    environment:
      - DJANGO_ADDESS=pwm
      - DJANGO_PORT=88
      - WEB_PORT=8080
    depends_on:
      - pwm

  
